import Head from 'next/head';
import useTranslation from 'next-translate/useTranslation';
import type { NextPage } from 'next';

const Home: NextPage = () => {
	const { t } = useTranslation();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<p>{t('common:title')}</p>
		</>
	);
};

export default Home;
