import Head from 'next/head';
import useTranslation from 'next-translate/useTranslation';
import { API_KEY_EXPERIENCE } from '@/api/constants';
import { client } from '@/api/utils';
import { useTheme } from '@/hooks/useTheme';
import type { MicroCMSListExperience } from '@/api/types';
import type { GetStaticProps, NextPage } from 'next';

type Props = {
	data: { [API_KEY_EXPERIENCE]: MicroCMSListExperience };
};

const Home: NextPage<Props> = ({ data }) => {
	const { t } = useTranslation();

	const { toggleTheme } = useTheme();

	console.log(
		data[API_KEY_EXPERIENCE].contents,
		'TODO: Using this data to implement the component.',
	);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<p>{t('common:title')}</p>
			<button onClick={toggleTheme}>{'Switch'}</button>
		</>
	);
};

export const getStaticProps: GetStaticProps<Props> = async () => {
	const experiences = await client.v1.experiences.$get();

	return {
		props: {
			data: {
				[API_KEY_EXPERIENCE]: experiences,
			},
		},
	};
};

export default Home;
